### ISSUE TITLE
Deploying an existing Lex.Db database in to WinRT app

### ISSUE THREAD

**Issue by nanddonet** [demigor/lex.db#23]
Hi, 

I´m creating a Lex.Db database from a WPF app, I´m adding this files to the WinRT project.

```
var root = string.Format("{0}\\{1}", Package.Current.InstalledLocation.Path, "Data\\Lex.Db");
           
            _db = new DbInstance("PersonDb", root);
            _db.Map<Person>().Automap(i => i.MID);
            _db.Initialize();

```

But an IO not found exceptio is thrown. I don´t want to create or copy manually my database to the IsolatedStorageFile, because I already have it there, in the Appx folder. Is there any way to tell lex.db to work againts that path? regards.

**Comment by demigor** [comment]
You need to pack your database files into Lex.Db\<DbName> project folder. For instance, if your database named "Demo", copy all *.data and *.index files into <YourProjectRoot>\Lex.Db\Demo folder, include all these files into your project and set their Build Action -> Content and Copy to Output Directory -> Copy if newer.

Unfortunately, application deployment folder in WinRT is read only. So you cannot modify any data located there.
