### ISSUE TITLE
System.NullReferenceException on Save

### ISSUE THREAD

**Issue by maxindahouze** [demigor/lex.db#27]
I'm trying to use lex.db in windows phone 8.1 universal app with latest nuget available version 1.2.2
Simple code on Save throws exeption

           db = new DbInstance("rebloged");
           db.Map<Rebloged>()
              .Automap(i => i.Id, true)
              .WithIndex("re", i => i.ReId);

            db.Initialize();

            db.Save(new Rebloged { ReId = "Lex" },
                    new Rebloged { ReId = "John" },
                    new Rebloged { ReId = "Scott" },
                    new Rebloged { ReId = "John" });

    public class Rebloged
    {
        public int Id { get; set; }
        public string ReId { get; set; } 
    }

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Lex.Db.Indexing.DataIndex`2.Update(IKeyNode keyNode, T instance)
   at Lex.Db.DbTable`1.WriteObjectData(IDbTableWriter writer, T instance, Byte[] data, Int32 length)
   at Lex.Db.DbTable`1.Save(IEnumerable`1 items)
   at Lex.Db.DbInstance.Save[T](T[] items)
```

Sample project - https://yadi.sk/d/g8Wf_nL1fxvP5

**Comment by demigor** [comment]
Fixed in 1.2.3. (My bad, occasionally committed experimental part of code).
