### ISSUE TITLE
LoadByCompositeKey?

### ISSUE THREAD

**Issue by MJ33** [demigor/lex.db#28]
How is it possible to load an entity by a composite primary key?

I would like to load an entity as follows:

Person person = databaseInstance.LoadByCompositeKey<Person>(pk1, pk2);

**Comment by demigor** [comment]
You define composite primary key by combining all PK fields into one distinct expression.
In your example, you may define a function like this:

string MyComplexKey(MyEntity e) { return  e.PK1 + (char)1 + e.PK2; }

Later on, use MyComplexKey function to construct this composite key and pass it into normal LoadByKey function. Unfortunately, key range queries are complicated for such composite keys.
