### ISSUE TITLE
Windows 10 Universal App Platform error

### ISSUE THREAD

**Issue by help-14** [demigor/lex.db#29]
HI, I'm using 1.2.4 on UAP, but when I get/save anything with lex.db it will throw 'System.InvalidOperationException' in Lex.Db.dll. When I check the LocalState folder of the app, the lex.db folder has nothing inside.
![capture](https://cloud.githubusercontent.com/assets/574357/9400315/53d07b7e-47ea-11e5-9c33-16e3e74d20f2.PNG)
![capture1](https://cloud.githubusercontent.com/assets/574357/9400314/53d05842-47ea-11e5-8c67-50a11df314ba.PNG)

**Comment by help-14** [comment]
Got the source and found the problem: Additional information: The expression 'Equal' is not supported for nullable type 'System.Nullable`1[System.DateTimeOffset]'

**Comment by bartlannoeye** [comment]
Got the same with System.Nullable'1[System.Guid]

**Comment by bartlannoeye** [comment]
Confirming this is fixed with the latest stable package (1.2.5)

**Comment by demigor** [comment]
Looks like CLR works differently with nullable type under UWP. Had to implement compare with null operation using alternative approach.
