### ISSUE TITLE
Same model objects in different tables

### ISSUE THREAD

**Issue by facundomedica** [demigor/lex.db#46]
I want to have like multiple tables with the same type of object and not getting them in the same place. Is it possible? Currently I'm doing it by creating different DbInstances. Is this right?

**Comment by demigor** [comment]
It is one of the possible scenarios. 

You may also subclass DbInstance differently, place all mapping initialization in constructor and provide different database path. Then you instantiate corresponding subclass and get things done.

Sorry, for late response.
